### ISSUE TITLE
Add support for HA deployments

### ISSUE THREAD

**Issue by facundofc** [canonical/charm-prometheus-juju-exporter#11]
The exporter's `controller-url` accepts only a single URL as its value, hurting the exporter's potential to be HA.

Suppose you have an HA juju controller with the [juju-controller charm](https://charmhub.io/juju-controller) deployed to each of the controllers. You deploy the `prometheus-juju-exporter` charm to the controller model and relate it to the `juju-controller` app. Then you get 3 exporters, one on each controller. You could think that if one of the controllers goes down, then the exporter would continue to work. But that is only the case if the down controller isn't the one specified in the `controller-url` config. If that one goes down, then there won't be any more metrics.

**Comment by aieri** [comment]
@facundofc if you deploy the exporter as a subordinate of a controller machine could you simply set controller-url to localhost?

**Comment by facundofc** [comment]
> @facundofc if you deploy the exporter as a subordinate of a controller machine could you simply set controller-url to localhost?

Indeed, that's a good idea. I'd document it properly on the property and on the charm docs as well as it is not obvious.

A consequence of this too is that if a controller _process_ crashes (as opposed to the whole machine hosting the controller going down), then we're losing an exporter when we didn't really had to. I believe we can live with this though.
