### ISSUE TITLE
Update README to align with the current state

### ISSUE THREAD

**Issue by agileshaw** [canonical/charm-prometheus-juju-exporter#51]
When the README was initially created, neither the Prometheus Juju Exporter snap or charm is published, so we were asking the users to manually build and deploy the packages. Now that they are officially published ([snap](https://snapcraft.io/prometheus-juju-exporter), [charm](https://charmhub.io/prometheus-juju-exporter)), we should replace this part of README and update it according to its [discourse documentation](https://discourse.charmhub.io/t/prometheus-juju-exporter-docs-index/11197). 

Additionally, integration with COS is the new standard and the README should reflect that.

It would also be great to make other enhancements to the README by taking references of the documentation.

**Comment by Pjack** [comment]
Updated in

https://charmhub.io/prometheus-juju-exporter
https://charmhub.io/prometheus-juju-exporter/docs/h-cos
